import React from "react";

export default function SummaryPanel({ data, showToast }) {
  function copyMarkdown() {
    const md = `# ${data.title}\n> ${data.channel} · ${data.duration}\n\n## Summary\n${data.summary}\n\n## Key Takeaways\n${data.keyPoints.map((p) => `- ${p}`).join("\n")}\n\n## Chapters\n${data.chapters.map((c) => `- **${c.timestamp}** — ${c.title}: ${c.description}`).join("\n")}\n\n## Q&A\n${data.qa.map((q) => `**Q: ${q.question}**\nA: ${q.answer}`).join("\n\n")}\n\n## Flashcards\n${data.flashcards.map((f) => `**${f.term}**: ${f.definition}`).join("\n\n")}`;
    navigator.clipboard.writeText(md).then(() => showToast("Copied as Markdown ✓"));
  }

  function exportPDF() {
    const w = window.open("", "_blank");
    w.document.write(`<!DOCTYPE html><html><head><title>VidBrain — ${data.title}</title>
<style>body{font-family:Georgia,serif;max-width:700px;margin:40px auto;padding:0 20px;color:#1a1a1a;line-height:1.7}h1{font-size:24px}h2{font-size:16px;color:#e05a2b;border-bottom:1px solid #eee;padding-bottom:6px;margin-top:28px}.meta{font-size:13px;color:#666;margin-bottom:24px}ul{padding-left:20px}li{margin-bottom:6px}.ch{display:flex;gap:12px;margin-bottom:10px}.ts{background:#e05a2b;color:white;padding:2px 8px;border-radius:4px;font-size:12px;font-family:monospace;white-space:nowrap;align-self:flex-start;margin-top:2px}.qa{margin-bottom:14px}.q{font-weight:bold;margin-bottom:4px}.fc-grid{display:grid;grid-template-columns:1fr 1fr;gap:10px}.fc{border:1px solid #ddd;border-radius:8px;padding:12px}.fc-term{font-weight:bold;color:#e05a2b;margin-bottom:4px}.fc-def{font-size:13px;color:#444}</style>
</head><body>
<h1>${data.title}</h1><p class="meta">${data.channel} · ${data.duration} · Generated by VidBrain</p>
<h2>Summary</h2><p>${data.summary}</p>
<h2>Key Takeaways</h2><ul>${data.keyPoints.map((p) => `<li>${p}</li>`).join("")}</ul>
<h2>Chapters</h2>${data.chapters.map((c) => `<div class="ch"><span class="ts">${c.timestamp}</span><div><strong>${c.title}</strong><br><small>${c.description}</small></div></div>`).join("")}
<h2>Q&A</h2>${data.qa.map((q) => `<div class="qa"><p class="q">Q: ${q.question}</p><p>A: ${q.answer}</p></div>`).join("")}
<h2>Flashcards</h2><div class="fc-grid">${data.flashcards.map((f) => `<div class="fc"><div class="fc-term">${f.term}</div><div class="fc-def">${f.definition}</div></div>`).join("")}</div>
</body></html>`);
    w.document.close();
    setTimeout(() => w.print(), 500);
  }

  return (
    <div>
      <div className="text-sm leading-relaxed p-5 rounded-2xl mb-5"
        style={{ background: "#131316", border: "1px solid rgba(255,255,255,0.07)", color: "#9b9a96", lineHeight: "1.8" }}>
        {data.summary}
      </div>
      <p className="text-xs font-bold tracking-widest uppercase mb-3" style={{ color: "#5a5958" }}>Key Takeaways</p>
      <ul className="flex flex-col gap-2 mb-6">
        {data.keyPoints.map((point, i) => (
          <li key={i} className="flex gap-3 items-start px-4 py-3 rounded-xl text-sm"
            style={{ background: "#131316", border: "1px solid rgba(255,255,255,0.07)" }}>
            <div className="w-1.5 h-1.5 rounded-full flex-shrink-0 mt-1.5" style={{ background: "#e05a2b" }} />
            {point}
          </li>
        ))}
      </ul>
      <div className="flex flex-wrap gap-2 pt-4" style={{ borderTop: "1px solid rgba(255,255,255,0.07)" }}>
        {[["⬇ Export PDF", exportPDF, true], ["📋 Copy Markdown", copyMarkdown, false], ["🔗 Notion", () => showToast("Coming soon!"), false], ["📚 Anki", () => showToast("Coming soon!"), false]].map(([label, fn, accent]) => (
          <button key={label} onClick={fn} className="text-xs font-semibold px-3 py-2 rounded-lg"
            style={{ border: `1px solid ${accent ? "rgba(224,90,43,0.3)" : "rgba(255,255,255,0.07)"}`, background: "transparent", color: accent ? "#e05a2b" : "#9b9a96", cursor: "pointer" }}>
            {label}
          </button>
        ))}
      </div>
    </div>
  );
}